

services:
  api-solid:
    image: bitnami/postgresql
    ports:
      - 5432:5432

    environment:
      - POSTGRESQL_USERNAME=solid
      - POSTGRESQL_PASSWORD=solid
      - POSTGRESQL_DATABASE=solid